version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password

  web:
    build: .
    environment:
      RAILS_ENV: test
      DATABASE_URL: "mysql2://root:password@db/cooking_selector_test"
    depends_on:
      - db

  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
