version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build: .
    env_file:
      - .env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/cooking_selector
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
  selenium:
    image: selenium/standalone-chrome
    platform: linux/amd64
    shm_size: 2gb
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
    
volumes:
  mysql-data:
    driver: local
