version: 2.1

orbs:
  heroku: circleci/heroku@2.0

jobs:
  build_and_test:
    docker:
      - image: cimg/ruby:3.0.2
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Install Dockerize
          command: |
            wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz
            tar -xzvf dockerize-linux-amd64-v0.6.1.tar.gz -C /usr/local/bin
      - run:
          name: Build and start containers
          command: |
            docker-compose up -d
            dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Setup database
          command: |
            docker-compose exec web rails db:setup
      - run:
          name: Run tests
          command: |
            docker-compose exec web rspec
            docker-compose exec web rubocop

  heroku_deploy:
    docker:
      - image: cimg/ruby:3.0.2
    steps:
      - checkout
      - heroku/install
      - run:
          name: Deploy to Heroku
          command: |
            heroku git:remote -a $HEROKU_APP_NAME
            git push heroku main:master

workflows:
  version: 2.1
  build_deploy:
    jobs:
      - build_and_test
      - heroku_deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: main
