version: 2.1

orbs:
  heroku: circleci/heroku@2.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.2
      - image: mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: myapp_test
      - image: selenium/standalone-chrome:latest
    environment:
      RAILS_ENV: test
      MYSQL_HOST: mysql
      DATABASE_URL: "mysql2://root:password@mysql/myapp_test"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y libmysqlclient-dev
            gem install bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name: Wait for DB
          command: |
            dockerize -wait tcp://mysql:3306 -timeout 2m
      - run:
          name: Setup Database
          command: |
            bundle exec rails db:create
            bundle exec rails db:schema:load
      - run:
          name: Run RuboCop
          command: bundle exec rubocop
      - run:
          name: Run RSpec Tests
          command: bundle exec rspec
      - run:
          name: Precompile assets
          command: |
            bundle exec rake assets:precompile

  heroku_deploy:
    working_directory: ~/potepanec
    executor: heroku/default
    resource_class: small
    steps:
      - checkout
      - heroku/install
      - run:
          name: Deploy
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:main
      - run:
          name: Run post-deploy tasks
          command: |
            heroku run bin/rails db:migrate -a $HEROKU_APP_NAME

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - heroku_deploy:
          requires:
            - build
          filters:
            branches:
              only: main
