version: 2.1

orbs:
  ruby: circleci/ruby@1.1
  heroku: circleci/heroku@1.2.6

jobs:
  build_and_test:
    docker:
      - image: cimg/ruby:3.1.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Install Docker Compose
          command: |
            # Update this comment to force a cache refresh
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

      - run:
          name: Run Docker Compose and Tests
          command: |
            docker-compose -f docker-compose.ci.yml up --build -d
            docker-compose -f docker-compose.ci.yml run --rm web bash -c "dockerize -wait tcp://db:3306 -timeout 1m"
            docker-compose -f docker-compose.ci.yml run web yarn install --force
            docker-compose -f docker-compose.ci.yml run web bundle exec rails webpacker:compile
            docker-compose -f docker-compose.ci.yml run web bundle exec rails db:prepare
            docker-compose -f docker-compose.ci.yml run web bundle exec rspec
            docker-compose -f docker-compose.ci.yml run web bundle exec rubocop
            docker-compose -f docker-compose.ci.yml down

  deploy:
    docker:
      - image: cimg/ruby:3.1.0
    steps:
      - checkout
      - heroku/install
      - run:
          name: Deploy to Heroku
          command: |
            heroku git:remote -a $HEROKU_APP_NAME
            git push heroku $CIRCLE_BRANCH:main

workflows:
  version: 2
  build_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: master
